### ISSUE TITLE
extend world to 30000

### ISSUE THREAD

**Issue by laika-murasaki** [laika-murasaki/Light-Minecraft#11]

**Comment by Laika1111** [comment]
pre generate

**Comment by Laika1111** [comment]
[07:27:24 INFO]: [Chunky] Task running for map. Processed: 927430 chunks (6.59%), ETA: 6:51:23, Rate: 532.4 cps,

**Comment by Laika1111** [comment]
17:21:26 INFO]: [Chunky] Task running for map. Processed: 2229929 chunks (15.85%), ETA: 149:33:17, Rate: 22.0 cps

**Comment by laika-murasaki** [comment]
18% 2487668 chunks ETA: 129:17:48

**Comment by laika-murasaki** [comment]
19%

**Comment by laika-murasaki** [comment]
23%

**Comment by laika-murasaki** [comment]
29%

**Comment by laika-murasaki** [comment]
พอละนานก่อน แค่ 16000 พอ
